# CMake generated Testfile for 
# Source directory: /home/yons/ROS/catkin_ws/src
# Build directory: /home/yons/ROS/catkin_ws/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("DSO_EX_1104")
subdirs("dso_execution")
subdirs("dso_test")
subdirs("Hardwares/ros_control/ros_control")
subdirs("Hardwares/ros_control/rqt_controller_manager")
subdirs("Hardwares/ros_control/controller_manager_msgs")
subdirs("tb3_modified_manipulation_moveit_config")
subdirs("Hardwares/UR/src/fmauch_universal_robot/universal_robots")
subdirs("ur3_wz_ag95_moveit_config")
subdirs("Hardwares/UR/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs")
subdirs("Hardwares/ros_control/hardware_interface")
subdirs("Hardwares/ros_control/combined_robot_hw")
subdirs("Hardwares/ros_control/controller_interface")
subdirs("Hardwares/UR/src/dh_robotics_ag95_description")
subdirs("Hardwares/ros_control/controller_manager")
subdirs("Hardwares/ros_control/controller_manager_tests")
subdirs("Hardwares/ros_control/combined_robot_hw_tests")
subdirs("Hardwares/UR/src/Universal_Robots_ROS_Driver/controller_stopper")
subdirs("Hardwares/ros_control/transmission_interface")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur_description")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur_gazebo")
subdirs("Hardwares/ros_control/joint_limits_interface")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur_kinematics")
subdirs("Hardwares/vicon_bridge")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur10_moveit_config")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur10e_moveit_config")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur16e_moveit_config")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur3_moveit_config")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur3e_moveit_config")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur5_moveit_config")
subdirs("Hardwares/UR/src/fmauch_universal_robot/ur5e_moveit_config")
subdirs("Hardwares/UR/src/Universal_Robots_ROS_Driver/ur_robot_driver")
subdirs("Hardwares/UR/src/Universal_Robots_ROS_Driver/ur_calibration")
